spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lastHomework?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: asd123456
resource:
  constant: /Users/peng/Downloads