spring:
  profiles:
    active: dev
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    encoding: UTF-8
    suffix: .html
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${resource.constant}
  aop:
    auto: true
    proxy-target-class: true
server:
  servlet:
    context-path: /text_project
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml