spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/lastHomework?useAffectedRows=true&serverTimezone=GMT&useSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: asd123456
resource:
  constant: /usr/local/tomcat/photo/